### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by nickgithubuser2** [nickgitubuser1/github-crash-course-1#1]
I think it looks better is the main title is a bit more orange.

The styling rule could be changed like this:

```css

h1 {
  color: #efa82e;
}

```
